<script>
    import { base } from '$app/paths';

    let { challenges } = $props();
    console.log(base)
</script>

<div class="container">
    <h1>Coding Challenge Log</h1>

    <div class="table-wrapper">
        <table class="responsive-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Challenge</th>
                    <th>Source</th>
                </tr>
            </thead>
            <tbody>
                <!-- TODO: include keyed option -->
                {#each challenges as c, i (i)}
                <tr>
                    <td data-label="Date">{c.date}</td>
                    <td data-label="Challenge"><a href="{base}/{c.challengeLink}">{c.challenge}</a></td>
                    <td data-label="Source"><a href={c.sourceURL}>{c.sourceLabel}</a></td>
                </tr>
                {/each}
                <!-- <tr>
                    <td data-label="Date">2025-06-15</td>
                    <td data-label="Challenge">Create a responsive pricing table component.</td>
                    <td data-label="Source"><a href="#">Frontend Mentor</a></td>
                </tr>
                <tr>
                    <td data-label="Date">2025-06-17</td>
                    <td data-label="Challenge">Build a functional JavaScript calculator.</td>
                    <td data-label="Source"><a href="#">CodePen Challenge</a></td>
                </tr>
                <tr>
                    <td data-label="Date">2025-06-20</td>
                    <td data-label="Challenge">Design the UI for a modern weather application.</td>
                    <td data-label="Source"><a href="#">Dribbble Weekly Warm-up</a></td>
                </tr>
                <tr>
                    <td data-label="Date">2025-06-22</td>
                    <td data-label="Challenge">Implement a dark and light mode theme toggle.</td>
                    <td data-label="Source"><a href="#">Dev.to Community</a></td>
                </tr> -->
            </tbody>
        </table>
    </div>
</div>

<style>
    /* Generated by Gemini AI: https://g.co/gemini/share/81632f30aa2e */
    /* Main Container and Typography */
    .container {
        width: 100%;
    }

    h1 {
        font-size: 1.875rem; /* text-3xl */
        font-weight: 700;
        text-align: center;
        margin-bottom: 1.5rem; /* mb-6 */
        color: #111827; /* gray-900 */
    }

    /* Table Wrapper for shadow and rounded corners */
    .table-wrapper {
        width: 100%;
        overflow-x: auto;
        background-color: #ffffff;
        border-radius: 0.5rem; /* rounded-lg */
        box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06);
    }

    /* General Table Styling */
    .responsive-table {
        width: 100%;
        border-collapse: collapse;
    }

    /* Table Header */
    .responsive-table thead {
        background-color: #f3f4f6; /* gray-100 */
        border-bottom: 2px solid #e5e7eb; /* border-gray-200 */
    }

    .responsive-table th {
        padding: 1rem;
        text-align: left;
        font-size: 0.875rem; /* text-sm */
        font-weight: 600; /* font-semibold */
        color: #4b5563; /* gray-600 */
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }

    /* Table Body */
    .responsive-table tbody tr {
        border-bottom: 1px solid #e5e7eb; /* divide-gray-200 */
    }

    .responsive-table tbody tr:last-child {
        border-bottom: 0;
    }

    .responsive-table td {
        padding: 1rem;
        white-space: nowrap;
    }

    /* Specific cell styling to match Tailwind example */
    .responsive-table td[data-label="Challenge"] {
        white-space: normal;
    }

    .responsive-table a {
        color: #2563eb; /* text-blue-600 */
        text-decoration: none;
    }

    .responsive-table a:hover {
        color: #1d4ed8; /* hover:text-blue-800 */
        text-decoration: underline;
    }
    
    /* Footer Text */
    .footer-text {
        text-align: center;
        font-size: 0.875rem; /* text-sm */
        color: #6b7280; /* text-gray-500 */
        margin-top: 1rem;
    }

    /* CORE RESPONSIVE LOGIC */
    @media screen and (max-width: 767px) {

        .table-wrapper {
            width: 100%;
            overflow-x: auto;
            background-color: #ffffff;
            border-radius: 0.5rem; /* rounded-lg */
            /* box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06); */
        }

        /* Hide the original table headers */
        .responsive-table thead {
            display: none;
        }

        /* Make table elements behave like blocks */
        /* .responsive-table, .responsive-table tbody, .responsive-table tr, .responsive-table td {
            display: block;
            width: 100%;
        } */

        .responsive-table, .responsive-table tbody, .responsive-table tr {
            display: block;
            width: 100%;
        }

        /* Style rows as cards */
        .responsive-table tr {
            margin-bottom: 1rem;
            border: 1px solid #e5e7eb;
            border-radius: 0.5rem;
            overflow: auto;
        }
        
        .responsive-table tr:last-child {
            margin-bottom: 0;
        }

        /* Style data cells for the stacked view */
        .responsive-table td {
            display: block;
            text-align:right;
            padding-left: 50%;
            position: relative;
            border-bottom: 1px solid #e5e7eb;
            /* Allow all cells to wrap text */
            white-space: normal; 
        }

        .responsive-table td:first-child {
            background-color: #f3f4f6; /* gray-100 */
        }

        .responsive-table td:last-child {
            border-bottom: 0;
        }

        /* Use ::before to add the data label */
        .responsive-table td::before {
            content: attr(data-label);
            position: absolute;
            left: 0;
            width: 45%;
            padding-left: 1rem;
            font-weight: 500;
            text-align: left;
            white-space: nowrap;
        }
    }
</style>